include:
  - project: 'vincenttunru/ci-templates'
    file: '/npm-node10.gitlab-ci.yml'

cache:
  paths:
    - website/node_modules

pages:
  stage: build
  script:
    - yarn
    - yarn run api-docs
    - cd website
    - yarn
    - yarn run build
    - mv build/tripledoc ../public/
  artifacts:
    paths:
    - public
    - website/sidebars.json
    - website/i18n/
  only:
    - master
